site_name: My Docs
nav:
    - Home: index.md
    - 1 - Vector Analysis:
      - 1.1 - Vector Algebra: ch1-1.md
      - 1.2 - Differential Calculus: ch1-2.md
      - 1.3 - Integral Calculus: ch1-3.md
      - 1.4 - Curvilinear Coordinates: ch1-4.md
      - 1.5 - The Dirac Delta Function: ch1-5.md
      - 1.6 - The Theory of Vector Fields: ch1-6.md
    - 2 - Electrostatics:
      - 2.1 - The Electric Field: ch2-1.md
      - 2.2 - Divergence and Curl of Electrostatic Fields: ch2-2.md
      - 2.3 - Electric Potential: ch2-3.md
      - 2.4 - Work and Energy in Electrostatics: ch2-4.md
      - 2.5 - Conductors: ch2-5.md
    - 3 - Potentials:
      - 3.1 - Laplace's Equation: ch3-1.md
      - 3.2 - The Method of Images: ch3-2.md
      - 3.3 - Separation of Variables: ch3-3.md
      - 3.4 - Multipole Expansion: ch3-4.md
      - Problems: problems-ch3.md
    - 4 - Electric Fields in Matter:
      - 4.1 - Polarization: ch4-1.md
      - 4.2 - The Field of a Polarized Object: ch4-2.md
      - 4.3 - The Electric Displacement: ch4-3.md
      - 4.4 - Linear Dielectrics: ch4-4.md
    - 5 - Magnetostatics:
      - 5.1 - The Lorentz Force Law: ch5-1.md
      - 5.2 - The Biot-Savart Law: ch5-2.md
      - 5.3 - The Divergence and Curl of B: ch5-3.md
      - 5.4 - Magnetic Vector Potential: ch5-4.md
      - Problems: problems-ch5.md
    - 6 - Magnetic Fields in Matter:
      - 6.1 - Magnetization: ch6-1.md
      - 6.2 - The Field of a Magnetized Object: ch6-2.md
      - 6.3 - The Auxiliary Field: ch6-3.md
      - 6.4 - Linear and Nonlinear Media: ch6-4.md
    - 7 - Electrodynamics:
      - 7.1 - Electromotive Force: ch7-1.md
      - 7.2 - Electromagnetic Induction: ch7-2.md
      - 7.3 - Maxwell's Equations: ch7-3.md
      - Problems: problems-ch7.md
    - 8 - Conservation Laws:
      - 8.0 - Phys544 Introduction: ch8-0.md
      - 8.1 - Charge and Energy: ch8-1.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  font:
    # text: 'Noto Serif'
    # code: 'Roboto Mono'
  text: IBM Plex Sans
  code: IBM Plex Mono
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'light blue'
  direction:
  favicon: assets/images/favicon.png
  logo:
    icon: "book"
  include_search_page: true
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: 'PeppyHare/griffiths-em'
repo_url: 'https://github.com/PeppyHare/griffiths-em'


# This lets us render MathJax, the coolest thing since sliced bread!
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  - extra.js
markdown_extensions:
  - mdx_math
  - admonition