site_name: My Docs
nav:
    - Home: index.md
    - 1 - Vector Analysis: ch1.md
    - 2 - Electrostatics: ch2.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  # custom_dir: 'mkdocs-material/material'
  font:
    text: 'Noto Serif'
    code: 'Roboto Mono'
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'light blue'
  direction:
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: 'PeppyHare/griffiths-em'
repo_url: 'https://github.com/PeppyHare/griffiths-em'


# This lets us render MathJax, the coolest thing since sliced bread!
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
  - extra.js
markdown_extensions:
  - mdx_math