site_name: My Docs
nav:
    - Home: index.md
    - 1 - Vector Analysis:
      - 1.1 - Vector Algebra: ch1-1.md
      - 1.2 - Differential Calculus: ch1-2.md
      - 1.3 - Integral Calculus: ch1-3.md
      - 1.4 - Curvilinear Coordinates: ch1-4.md
      - 1.5 - The Dirac Delta Function: ch1-5.md
      - 1.6 - The Theory of Vector Fields: ch1-6.md
    - 2 - Electrostatics:
      - 2.1 - The Electric Field: ch2-1.md
      - 2.2 - Divergence and Curl of Electrostatic Fields: ch2-2.md
      - 2.3 - Electric Potential: ch2-3.md
      - 2.4 - Work and Energy in Electrostatics: ch2-4.md
      - 2.5 - Conductors: ch2-5.md
    - 3 - Potentials:
      - 3.1 - Laplace's Equation: ch3-1.md
      - 3.2 - The Method of Images: ch3-2.md
      - 3.3 - Separation of Variables: ch3-3.md
      - 3.4 - Multipole Expansion: ch3-4.md
    - 4 - Electric Fields in Matter:
      - 4.1 - Polarization: ch4-1.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  font:
    text: 'Noto Serif'
    code: 'Roboto Mono'
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'light blue'
  direction:
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
  include_search_page: true
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: 'PeppyHare/griffiths-em'
repo_url: 'https://github.com/PeppyHare/griffiths-em'


# This lets us render MathJax, the coolest thing since sliced bread!
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  - extra.js
markdown_extensions:
  - mdx_math
  - admonition